// <auto-generated />
using System;
using Common.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216093010_AddAssessmentEntities")]
    partial class AddAssessmentEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.AnswerTranslate", b =>
                {
                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerId", "Language");

                    b.ToTable("AnswerTranslates", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiffEx")
                        .HasColumnType("int");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LevelVision")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("ToGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalEx")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Codes", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.CodeTranslate", b =>
                {
                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CodeId", "Language");

                    b.ToTable("CodeTranslates", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HeadId")
                        .HasColumnType("int");

                    b.Property<string>("LastNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("M1Id")
                        .HasColumnType("int");

                    b.Property<int?>("M2Id")
                        .HasColumnType("int");

                    b.Property<int?>("M3Id")
                        .HasColumnType("int");

                    b.Property<int?>("M4Id")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManagerialLevelValueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfessionalLevelValueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RMId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.HasIndex("M1Id");

                    b.HasIndex("M2Id");

                    b.HasIndex("M3Id");

                    b.HasIndex("M4Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RMId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.ManagerialLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ManagerialLevels", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.MeetingRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("MeetingRequestStatuses", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.ProcessConfirmationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProcessConfirmationStatuses", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.ProfessionalLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProfessionalLevels", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubTopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubTopicId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.QuestionTranslate", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("QuestionId", "Language");

                    b.ToTable("QuestionTranslates", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.SkillLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SkillLevels", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.Subtopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subtopics", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.SubtopicTranslate", b =>
                {
                    b.Property<int>("SubtopicId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("SubtopicId", "Language");

                    b.ToTable("SubtopicTranslates", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.TopicTranslate", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("TopicId", "Language");

                    b.ToTable("TopicTranslates", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.YesNoOtherOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("YesNoOtherOptions", (string)null);
                });

            modelBuilder.Entity("Common.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Common.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.AnswerTranslate", b =>
                {
                    b.HasOne("Common.Domain.Entities.Answer", null)
                        .WithMany("AnswerTranslates")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.CodeTranslate", b =>
                {
                    b.HasOne("Common.Domain.Entities.Code", null)
                        .WithMany("CodeTranslates")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Common.Domain.Entities.Employee", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Common.Domain.Entities.Employee", "M1")
                        .WithMany()
                        .HasForeignKey("M1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Common.Domain.Entities.Employee", "M2")
                        .WithMany()
                        .HasForeignKey("M2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Common.Domain.Entities.Employee", "M3")
                        .WithMany()
                        .HasForeignKey("M3Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Common.Domain.Entities.Employee", "M4")
                        .WithMany()
                        .HasForeignKey("M4Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Common.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Common.Domain.Entities.Employee", "RM")
                        .WithMany()
                        .HasForeignKey("RMId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Head");

                    b.Navigation("M1");

                    b.Navigation("M2");

                    b.Navigation("M3");

                    b.Navigation("M4");

                    b.Navigation("Manager");

                    b.Navigation("RM");
                });

            modelBuilder.Entity("Common.Domain.Entities.Question", b =>
                {
                    b.HasOne("Common.Domain.Entities.Subtopic", null)
                        .WithMany()
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.QuestionTranslate", b =>
                {
                    b.HasOne("Common.Domain.Entities.Question", null)
                        .WithMany("QuestionTranslates")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.Subtopic", b =>
                {
                    b.HasOne("Common.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.SubtopicTranslate", b =>
                {
                    b.HasOne("Common.Domain.Entities.Subtopic", null)
                        .WithMany("SubtopicTranslates")
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.Template", b =>
                {
                    b.HasOne("Common.Domain.Entities.Code", null)
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.Topic", b =>
                {
                    b.HasOne("Common.Domain.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.TopicTranslate", b =>
                {
                    b.HasOne("Common.Domain.Entities.Topic", null)
                        .WithMany("TopicTranslates")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Domain.Entities.Answer", b =>
                {
                    b.Navigation("AnswerTranslates");
                });

            modelBuilder.Entity("Common.Domain.Entities.Code", b =>
                {
                    b.Navigation("CodeTranslates");
                });

            modelBuilder.Entity("Common.Domain.Entities.Question", b =>
                {
                    b.Navigation("QuestionTranslates");
                });

            modelBuilder.Entity("Common.Domain.Entities.Subtopic", b =>
                {
                    b.Navigation("SubtopicTranslates");
                });

            modelBuilder.Entity("Common.Domain.Entities.Topic", b =>
                {
                    b.Navigation("TopicTranslates");
                });
#pragma warning restore 612, 618
        }
    }
}
