<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Common.DAL</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configurations\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common.Domain\Common.Domain.csproj" />
    </ItemGroup>

</Project>
