// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureGaze.Infrastructure.Database;

#nullable disable

namespace PureGaze.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PureGaze.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AnswerTranslate", b =>
                {
                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerId", "Language");

                    b.ToTable("AnswerTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AssessmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("AssessmentRequests", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiffEx")
                        .HasColumnType("int");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalEx")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Codes", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.CodeTranslate", b =>
                {
                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("LevelVision")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("CodeId", "Language");

                    b.ToTable("CodeTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Hash")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("HeadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LifecycleStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("M1Id")
                        .HasColumnType("int");

                    b.Property<int?>("M2Id")
                        .HasColumnType("int");

                    b.Property<int?>("M3Id")
                        .HasColumnType("int");

                    b.Property<int?>("M4Id")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManagerialLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfessionalLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RMId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.HasIndex("M1Id");

                    b.HasIndex("M2Id");

                    b.HasIndex("M3Id");

                    b.HasIndex("M4Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RMId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.ManagerialLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OrderValue")
                        .HasColumnType("int");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ManagerialLevels", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.ProfessionalLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OrderValue")
                        .HasColumnType("int");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProfessionalLevels", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubTopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubTopicId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.QuestionTranslate", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("QuestionId", "Language");

                    b.ToTable("QuestionTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Subtopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subtopics", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.SubtopicTranslate", b =>
                {
                    b.Property<int>("SubtopicId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("SubtopicId", "Language");

                    b.ToTable("SubtopicTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodeId")
                        .IsUnique();

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.TopicTranslate", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("TopicId", "Language");

                    b.ToTable("TopicTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Answer", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AnswerTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Answer", null)
                        .WithMany("AnswerTranslates")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AssessmentRequest", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.CodeTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Code", null)
                        .WithMany("CodeTranslates")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Employee", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Employee", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M1")
                        .WithMany()
                        .HasForeignKey("M1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M2")
                        .WithMany()
                        .HasForeignKey("M2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M3")
                        .WithMany()
                        .HasForeignKey("M3Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M4")
                        .WithMany()
                        .HasForeignKey("M4Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "RM")
                        .WithMany()
                        .HasForeignKey("RMId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Head");

                    b.Navigation("M1");

                    b.Navigation("M2");

                    b.Navigation("M3");

                    b.Navigation("M4");

                    b.Navigation("Manager");

                    b.Navigation("RM");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Question", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Subtopic", null)
                        .WithMany()
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.QuestionTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Question", null)
                        .WithMany("QuestionTranslates")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Subtopic", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.SubtopicTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Subtopic", null)
                        .WithMany("SubtopicTranslates")
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Template", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Code", null)
                        .WithOne()
                        .HasForeignKey("PureGaze.Domain.Entities.Template", "CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Topic", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Template", null)
                        .WithMany("Topics")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.TopicTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Topic", null)
                        .WithMany("TopicTranslates")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Answer", b =>
                {
                    b.Navigation("AnswerTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Code", b =>
                {
                    b.Navigation("CodeTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Question", b =>
                {
                    b.Navigation("QuestionTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Subtopic", b =>
                {
                    b.Navigation("SubtopicTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Template", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Topic", b =>
                {
                    b.Navigation("TopicTranslates");
                });
#pragma warning restore 612, 618
        }
    }
}
