// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureGaze.Infrastructure.Database;

#nullable disable

namespace PureGaze.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PureGaze.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AnswerTranslate", b =>
                {
                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerId", "Language");

                    b.ToTable("AnswerTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AssessmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("AssessmentRequests", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AssessmentStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssessorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRecommended")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("AssessorId");

                    b.HasIndex("TopicId");

                    b.ToTable("AssessmentStages", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiffEx")
                        .HasColumnType("int");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalEx")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Codes", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.CodeTranslate", b =>
                {
                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("LevelVision")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("CodeId", "Language");

                    b.ToTable("CodeTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Hash")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("HeadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LifecycleStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("M1Id")
                        .HasColumnType("int");

                    b.Property<int?>("M2Id")
                        .HasColumnType("int");

                    b.Property<int?>("M3Id")
                        .HasColumnType("int");

                    b.Property<int?>("M4Id")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManagerialLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfessionalLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RMId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.HasIndex("M1Id");

                    b.HasIndex("M2Id");

                    b.HasIndex("M3Id");

                    b.HasIndex("M4Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ManagerialLevelId");

                    b.HasIndex("ProfessionalLevelId");

                    b.HasIndex("RMId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.EmployeeSettings", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeSettings", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.ManagerialLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderValue")
                        .HasColumnType("int");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ManagerialLevels", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.ProfessionalLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderValue")
                        .HasColumnType("int");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProfessionalLevels", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubTopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubTopicId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.QuestionTranslate", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("QuestionId", "Language");

                    b.ToTable("QuestionTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Subtopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subtopics", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.SubtopicScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("SubtopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("SubtopicId");

                    b.ToTable("SubtopicScores", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.SubtopicTranslate", b =>
                {
                    b.Property<int>("SubtopicId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("SubtopicId", "Language");

                    b.ToTable("SubtopicTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodeId")
                        .IsUnique();

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.TopicTranslate", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("TopicId", "Language");

                    b.ToTable("TopicTranslates", (string)null);
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Answer", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("PureGaze.Domain.Entities.Answer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AnswerTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Answer", null)
                        .WithMany("AnswerTranslates")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Code");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AssessmentRequest", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AssessmentStage", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Assessment", "Assessment")
                        .WithMany("Stages")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Employee", "Assessor")
                        .WithMany()
                        .HasForeignKey("AssessorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PureGaze.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Assessor");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.CodeTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Code", null)
                        .WithMany("CodeTranslates")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Employee", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Employee", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M1")
                        .WithMany()
                        .HasForeignKey("M1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M2")
                        .WithMany()
                        .HasForeignKey("M2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M3")
                        .WithMany()
                        .HasForeignKey("M3Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "M4")
                        .WithMany()
                        .HasForeignKey("M4Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PureGaze.Domain.Entities.ManagerialLevel", "ManagerialLevel")
                        .WithMany()
                        .HasForeignKey("ManagerialLevelId");

                    b.HasOne("PureGaze.Domain.Entities.ProfessionalLevel", "ProfessionalLevel")
                        .WithMany()
                        .HasForeignKey("ProfessionalLevelId");

                    b.HasOne("PureGaze.Domain.Entities.Employee", "RM")
                        .WithMany()
                        .HasForeignKey("RMId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Head");

                    b.Navigation("M1");

                    b.Navigation("M2");

                    b.Navigation("M3");

                    b.Navigation("M4");

                    b.Navigation("Manager");

                    b.Navigation("ManagerialLevel");

                    b.Navigation("ProfessionalLevel");

                    b.Navigation("RM");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.EmployeeSettings", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Employee", "Employee")
                        .WithOne("EmployeeSettings")
                        .HasForeignKey("PureGaze.Domain.Entities.EmployeeSettings", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Question", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Subtopic", "Subtopic")
                        .WithMany("Questions")
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtopic");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.QuestionTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Question", null)
                        .WithMany("QuestionTranslates")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Subtopic", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Topic", "Topic")
                        .WithMany("Subtopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.SubtopicScore", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.AssessmentStage", "Stage")
                        .WithMany("Scores")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureGaze.Domain.Entities.Subtopic", "Subtopic")
                        .WithMany()
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Subtopic");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.SubtopicTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Subtopic", null)
                        .WithMany("SubtopicTranslates")
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Template", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Code", null)
                        .WithOne()
                        .HasForeignKey("PureGaze.Domain.Entities.Template", "CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Topic", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Template", null)
                        .WithMany("Topics")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.TopicTranslate", b =>
                {
                    b.HasOne("PureGaze.Domain.Entities.Topic", null)
                        .WithMany("TopicTranslates")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Answer", b =>
                {
                    b.Navigation("AnswerTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.AssessmentStage", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Code", b =>
                {
                    b.Navigation("CodeTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();

                    b.Navigation("QuestionTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Subtopic", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SubtopicTranslates");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Template", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("PureGaze.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Subtopics");

                    b.Navigation("TopicTranslates");
                });
#pragma warning restore 612, 618
        }
    }
}
